/***
 * Exception generated by basic calculator.
 * @author Deepti Kamat
 *
 */
public class BCException extends Exception{
	/**
	 * Default serial version ID
	 */
	private static final long serialVersionUID = 1L;

	public BCException(String msg) {
		super("BCException :"+msg);
	}
}
